name: CyberStorm
on: [workflow_dispatch]
jobs:

  Art_Wave:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Set working directory
        run: cd D:\a\art-wave\art-wave\client
        
      - name: Local_Deployment
        run: npm run dev
