name: CyberStorm
on: [workflow_dispatch]
jobs:

  Art_Wave:
    runs-on: windows-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Set up Node.js
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: |
          npm install
          pip install flask
          pip install torch
          pip install Pillow
          pip install torchvision
          pip install numpy
          pip install warnings
          pip install glob
          pip install cv2
          pip install scikit-image

      - name: Local_Deployment
        run: npm run dev
